//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nicaragua.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CA_IP_SUCURSAL_DEPENDIENTE
    {
        public Nullable<int> Corte { get; set; }
        public Nullable<double> Valor_Lista { get; set; }
        public Nullable<double> IpTotal { get; set; }
        public string ClienteNombre { get; set; }
        public string Pais { get; set; }
        public Nullable<int> Anio { get; set; }
        public Nullable<int> Mes { get; set; }
        public string NombreCanal { get; set; }
        public double Producto { get; set; }
        public string Cliente { get; set; }
        public int Canal { get; set; }
        public Nullable<int> Incentivos { get; set; }
        public Nullable<int> IdLista { get; set; }
        public string descripcion { get; set; }
        public string Canje { get; set; }
        public Nullable<int> TipoCanje { get; set; }
        public Nullable<double> Unidades { get; set; }
        public Nullable<decimal> Promotor { get; set; }
        public string Nombre { get; set; }
        public string Usuario { get; set; }
        public string IPEstadoDesc { get; set; }
        public Nullable<byte> Semana { get; set; }
        public string Cod_Cliente { get; set; }
        public int IdSucursal { get; set; }
        public int IdDependiente { get; set; }
        public string Dependiente { get; set; }
        public string NProducto { get; set; }
        public string Sucursal { get; set; }
        public string Dependiente2 { get; set; }
        public string Factura { get; set; }
    }
}
