//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nicaragua.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DataManagementEntities : DbContext
    {
        public DataManagementEntities()
            : base("name=DataManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<SP_VALIDAR_DATOS_CORTES_NI_Result> SP_VALIDAR_DATOS_CORTES_NI(Nullable<int> aNIO, Nullable<int> mES, string cLIENTEPADRE)
        {
            var aNIOParameter = aNIO.HasValue ?
                new ObjectParameter("ANIO", aNIO) :
                new ObjectParameter("ANIO", typeof(int));
    
            var mESParameter = mES.HasValue ?
                new ObjectParameter("MES", mES) :
                new ObjectParameter("MES", typeof(int));
    
            var cLIENTEPADREParameter = cLIENTEPADRE != null ?
                new ObjectParameter("CLIENTEPADRE", cLIENTEPADRE) :
                new ObjectParameter("CLIENTEPADRE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_VALIDAR_DATOS_CORTES_NI_Result>("SP_VALIDAR_DATOS_CORTES_NI", aNIOParameter, mESParameter, cLIENTEPADREParameter);
        }
    }
}
