//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nicaragua.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DataManagementEntities1 : DbContext
    {
        public DataManagementEntities1()
            : base("name=DataManagementEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual int sp_valida_Genera_Genera_Con_Exclusion_Inclusion(string pais, string cliente, Nullable<int> promotor, string usuario, string observaciones, Nullable<int> corte, Nullable<int> anio, Nullable<int> mes, string excluirDocumentos, string incluirDocumentos, ObjectParameter salidaCorte, ObjectParameter salidaIdo, string clienteh)
        {
            var paisParameter = pais != null ?
                new ObjectParameter("Pais", pais) :
                new ObjectParameter("Pais", typeof(string));
    
            var clienteParameter = cliente != null ?
                new ObjectParameter("Cliente", cliente) :
                new ObjectParameter("Cliente", typeof(string));
    
            var promotorParameter = promotor.HasValue ?
                new ObjectParameter("Promotor", promotor) :
                new ObjectParameter("Promotor", typeof(int));
    
            var usuarioParameter = usuario != null ?
                new ObjectParameter("Usuario", usuario) :
                new ObjectParameter("Usuario", typeof(string));
    
            var observacionesParameter = observaciones != null ?
                new ObjectParameter("Observaciones", observaciones) :
                new ObjectParameter("Observaciones", typeof(string));
    
            var corteParameter = corte.HasValue ?
                new ObjectParameter("Corte", corte) :
                new ObjectParameter("Corte", typeof(int));
    
            var anioParameter = anio.HasValue ?
                new ObjectParameter("anio", anio) :
                new ObjectParameter("anio", typeof(int));
    
            var mesParameter = mes.HasValue ?
                new ObjectParameter("mes", mes) :
                new ObjectParameter("mes", typeof(int));
    
            var excluirDocumentosParameter = excluirDocumentos != null ?
                new ObjectParameter("ExcluirDocumentos", excluirDocumentos) :
                new ObjectParameter("ExcluirDocumentos", typeof(string));
    
            var incluirDocumentosParameter = incluirDocumentos != null ?
                new ObjectParameter("IncluirDocumentos", incluirDocumentos) :
                new ObjectParameter("IncluirDocumentos", typeof(string));
    
            var clientehParameter = clienteh != null ?
                new ObjectParameter("clienteh", clienteh) :
                new ObjectParameter("clienteh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_valida_Genera_Genera_Con_Exclusion_Inclusion", paisParameter, clienteParameter, promotorParameter, usuarioParameter, observacionesParameter, corteParameter, anioParameter, mesParameter, excluirDocumentosParameter, incluirDocumentosParameter, salidaCorte, salidaIdo, clientehParameter);
        }
    }
}
